version: '3'

services:

  db_postgres:
    restart: always
    image: postgres:11
    container_name: db_postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api_desafio:
    container_name: api_desafio
    restart: always
    build: .
    links:
      - db_postgres
    depends_on:
      - db_postgres
    ports:
      - 8000:8000
    volumes:
      - .:/jenkins-django-pipeline/
    command: /jenkins-django-pipeline/run.sh

volumes:
  postgres_data:

